// lấy toàn bộ danh sách người dùng

export const GET_ALL_FEATURE_SUCCESS = 'GET_ALL_FEATURE_SUCCESS';
export const GET_ALL_FEATURE_FAIL = 'GET_ALL_FEATURE_FAIL';
export const GET_FEATURE_DETAIL_SUCCESS = 'GET_FEATURE_DETAIL_SUCCESS';
export const GET_FEATURE_DETAIL_FAIL = 'GET_FEATURE_DETAIL_FAIL';
export const POST_FEATURE_SUCCESS = 'POST_FEATURE_SUCCESS';
export const POST_FEATURE_FAIL = 'POST_FEATURE_FAIL';
export const PUT_FEATURE_SUCCESS = 'PUT_FEATURE_SUCCESS';
export const PUT_FEATURE_FAIL = 'PUT_FEATURE_FAIL';
export const DELETE_FEATURE_SUCCESS = 'DELETE_FEATURE_SUCCESS';
export const DELETE_FEATURE_FAIL = 'DELETE_FEATURE_FAIL';
export const START_QUERY = 'START_QUERY';
