// lấy toàn bộ danh sách người dùng

export const GET_ALL_GENDER_SUCCESS = 'GET_ALL_GENDER_SUCCESS';
export const GET_ALL_GENDER_FAIL = 'GET_ALL_GENDER_FAIL';
export const GET_GENDER_DETAIL_SUCCESS = 'GET_GENDER_DETAIL_SUCCESS';
export const GET_GENDER_DETAIL_FAIL = 'GET_GENDER_DETAIL_FAIL';
export const POST_GENDER_SUCCESS = 'POST_GENDER_SUCCESS';
export const POST_GENDER_FAIL = 'POST_GENDER_FAIL';
export const PUT_GENDER_SUCCESS = 'PUT_GENDER_SUCCESS';
export const PUT_GENDER_FAIL = 'PUT_GENDER_FAIL';
export const DELETE_GENDER_SUCCESS = 'DELETE_GENDER_SUCCESS';
export const DELETE_GENDER_FAIL = 'DELETE_GENDER_FAIL';
export const START_QUERY = 'START_QUERY';
