// lấy toàn bộ danh sách người dùng

export const GET_ALL_MATERIAL_SUCCESS = 'GET_ALL_MATERIAL_SUCCESS';
export const GET_ALL_MATERIAL_FAIL = 'GET_ALL_MATERIAL_FAIL';
export const GET_MATERIAL_DETAIL_SUCCESS = 'GET_MATERIAL_DETAIL_SUCCESS';
export const GET_MATERIAL_DETAIL_FAIL = 'GET_MATERIAL_DETAIL_FAIL';
export const POST_MATERIAL_SUCCESS = 'POST_MATERIAL_SUCCESS';
export const POST_MATERIAL_FAIL = 'POST_MATERIAL_FAIL';
export const PUT_MATERIAL_SUCCESS = 'PUT_MATERIAL_SUCCESS';
export const PUT_MATERIAL_FAIL = 'PUT_MATERIAL_FAIL';
export const DELETE_MATERIAL_SUCCESS = 'DELETE_MATERIAL_SUCCESS';
export const DELETE_MATERIAL_FAIL = 'DELETE_MATERIAL_FAIL';
export const START_QUERY = 'START_QUERY';
