// lấy toàn bộ danh sách người dùng

export const GET_ALL_MODELPRODUCT_SUCCESS = 'GET_ALL_MODELPRODUCT_SUCCESS';
export const GET_ALL_MODELPRODUCT_FAIL = 'GET_ALL_MODELPRODUCT_FAIL';
export const GET_MODELPRODUCT_DETAIL_SUCCESS = 'GET_MODELPRODUCT_DETAIL_SUCCESS';
export const GET_MODELPRODUCT_DETAIL_FAIL = 'GET_MODELPRODUCT_DETAIL_FAIL';
export const POST_MODELPRODUCT_SUCCESS = 'POST_MODELPRODUCT_SUCCESS';
export const POST_MODELPRODUCT_FAIL = 'POST_MODELPRODUCT_FAIL';
export const PUT_MODELPRODUCT_SUCCESS = 'PUT_MODELPRODUCT_SUCCESS';
export const PUT_MODELPRODUCT_FAIL = 'PUT_MODELPRODUCT_FAIL';
export const DELETE_MODELPRODUCT_SUCCESS = 'DELETE_MODELPRODUCT_SUCCESS';
export const DELETE_MODELPRODUCT_FAIL = 'DELETE_MODELPRODUCT_FAIL';
export const START_QUERY = 'START_QUERY';
