// lấy toàn bộ danh sách người dùng

export const GET_ALL_NUMBERPART_SUCCESS = 'GET_ALL_NUMBERPART_SUCCESS';
export const GET_ALL_NUMBERPART_FAIL = 'GET_ALL_NUMBERPART_FAIL';
export const GET_NUMBERPART_DETAIL_SUCCESS = 'GET_NUMBERPART_DETAIL_SUCCESS';
export const GET_NUMBERPART_DETAIL_FAIL = 'GET_NUMBERPART_DETAIL_FAIL';
export const POST_NUMBERPART_SUCCESS = 'POST_NUMBERPART_SUCCESS';
export const POST_NUMBERPART_FAIL = 'POST_NUMBERPART_FAIL';
export const PUT_NUMBERPART_SUCCESS = 'PUT_NUMBERPART_SUCCESS';
export const PUT_NUMBERPART_FAIL = 'PUT_NUMBERPART_FAIL';
export const DELETE_NUMBERPART_SUCCESS = 'DELETE_NUMBERPART_SUCCESS';
export const DELETE_NUMBERPART_FAIL = 'DELETE_NUMBERPART_FAIL';
export const START_QUERY = 'START_QUERY';
