// lấy toàn bộ danh sách người dùng

export const GET_ALL_OPERATINGSYSTEM_SUCCESS = 'GET_ALL_OPERATINGSYSTEM_SUCCESS';
export const GET_ALL_OPERATINGSYSTEM_FAIL = 'GET_ALL_OPERATINGSYSTEM_FAIL';
export const GET_OPERATINGSYSTEM_DETAIL_SUCCESS = 'GET_OPERATINGSYSTEM_DETAIL_SUCCESS';
export const GET_OPERATINGSYSTEM_DETAIL_FAIL = 'GET_OPERATINGSYSTEM_DETAIL_FAIL';
export const POST_OPERATINGSYSTEM_SUCCESS = 'POST_OPERATINGSYSTEM_SUCCESS';
export const POST_OPERATINGSYSTEM_FAIL = 'POST_OPERATINGSYSTEM_FAIL';
export const PUT_OPERATINGSYSTEM_SUCCESS = 'PUT_OPERATINGSYSTEM_SUCCESS';
export const PUT_OPERATINGSYSTEM_FAIL = 'PUT_OPERATINGSYSTEM_FAIL';
export const DELETE_OPERATINGSYSTEM_SUCCESS = 'DELETE_OPERATINGSYSTEM_SUCCESS';
export const DELETE_OPERATINGSYSTEM_FAIL = 'DELETE_OPERATINGSYSTEM_FAIL';
export const START_QUERY = 'START_QUERY';
