// lấy toàn bộ danh sách người dùng

export const GET_ALL_ORIGIN_SUCCESS = 'GET_ALL_ORIGIN_SUCCESS';
export const GET_ALL_ORIGIN_FAIL = 'GET_ALL_ORIGIN_FAIL';
export const GET_ORIGIN_DETAIL_SUCCESS = 'GET_ORIGIN_DETAIL_SUCCESS';
export const GET_ORIGIN_DETAIL_FAIL = 'GET_ORIGIN_DETAIL_FAIL';
export const POST_ORIGIN_SUCCESS = 'POST_ORIGIN_SUCCESS';
export const POST_ORIGIN_FAIL = 'POST_ORIGIN_FAIL';
export const PUT_ORIGIN_SUCCESS = 'PUT_ORIGIN_SUCCESS';
export const PUT_ORIGIN_FAIL = 'PUT_ORIGIN_FAIL';
export const DELETE_ORIGIN_SUCCESS = 'DELETE_ORIGIN_SUCCESS';
export const DELETE_ORIGIN_FAIL = 'DELETE_ORIGIN_FAIL';
export const START_QUERY = 'START_QUERY';
