// lấy toàn bộ danh sách người dùng

export const GET_ALL_PROCESSOR_SUCCESS = 'GET_ALL_PROCESSOR_SUCCESS';
export const GET_ALL_PROCESSOR_FAIL = 'GET_ALL_PROCESSOR_FAIL';
export const GET_PROCESSOR_DETAIL_SUCCESS = 'GET_PROCESSOR_DETAIL_SUCCESS';
export const GET_PROCESSOR_DETAIL_FAIL = 'GET_PROCESSOR_DETAIL_FAIL';
export const POST_PROCESSOR_SUCCESS = 'POST_PROCESSOR_SUCCESS';
export const POST_PROCESSOR_FAIL = 'POST_PROCESSOR_FAIL';
export const PUT_PROCESSOR_SUCCESS = 'PUT_PROCESSOR_SUCCESS';
export const PUT_PROCESSOR_FAIL = 'PUT_PROCESSOR_FAIL';
export const DELETE_PROCESSOR_SUCCESS = 'DELETE_PROCESSOR_SUCCESS';
export const DELETE_PROCESSOR_FAIL = 'DELETE_PROCESSOR_FAIL';
export const START_QUERY = 'START_QUERY';
