// lấy toàn bộ danh sách người dùng

export const GET_ALL_SAMPLE_SUCCESS = 'GET_ALL_SAMPLE_SUCCESS';
export const GET_ALL_SAMPLE_FAIL = 'GET_ALL_SAMPLE_FAIL';
export const GET_SAMPLE_DETAIL_SUCCESS = 'GET_SAMPLE_DETAIL_SUCCESS';
export const GET_SAMPLE_DETAIL_FAIL = 'GET_SAMPLE_DETAIL_FAIL';
export const POST_SAMPLE_SUCCESS = 'POST_SAMPLE_SUCCESS';
export const POST_SAMPLE_FAIL = 'POST_SAMPLE_FAIL';
export const PUT_SAMPLE_SUCCESS = 'PUT_SAMPLE_SUCCESS';
export const PUT_SAMPLE_FAIL = 'PUT_SAMPLE_FAIL';
export const DELETE_SAMPLE_SUCCESS = 'DELETE_SAMPLE_SUCCESS';
export const DELETE_SAMPLE_FAIL = 'DELETE_SAMPLE_FAIL';
export const START_QUERY = 'START_QUERY';
