// lấy toàn bộ danh sách người dùng

export const GET_ALL_SCREENRESOLUTION_SUCCESS = 'GET_ALL_SCREENRESOLUTION_SUCCESS';
export const GET_ALL_SCREENRESOLUTION_FAIL = 'GET_ALL_SCREENRESOLUTION_FAIL';
export const GET_SCREENRESOLUTION_DETAIL_SUCCESS = 'GET_SCREENRESOLUTION_DETAIL_SUCCESS';
export const GET_SCREENRESOLUTION_DETAIL_FAIL = 'GET_SCREENRESOLUTION_DETAIL_FAIL';
export const POST_SCREENRESOLUTION_SUCCESS = 'POST_SCREENRESOLUTION_SUCCESS';
export const POST_SCREENRESOLUTION_FAIL = 'POST_SCREENRESOLUTION_FAIL';
export const PUT_SCREENRESOLUTION_SUCCESS = 'PUT_SCREENRESOLUTION_SUCCESS';
export const PUT_SCREENRESOLUTION_FAIL = 'PUT_SCREENRESOLUTION_FAIL';
export const DELETE_SCREENRESOLUTION_SUCCESS = 'DELETE_SCREENRESOLUTION_SUCCESS';
export const DELETE_SCREENRESOLUTION_FAIL = 'DELETE_SCREENRESOLUTION_FAIL';
export const START_QUERY = 'START_QUERY';
