// lấy toàn bộ danh sách người dùng

export const GET_ALL_SCREEN_SUCCESS = 'GET_ALL_SCREEN_SUCCESS';
export const GET_ALL_SCREEN_FAIL = 'GET_ALL_SCREEN_FAIL';
export const GET_SCREEN_DETAIL_SUCCESS = 'GET_SCREEN_DETAIL_SUCCESS';
export const GET_SCREEN_DETAIL_FAIL = 'GET_SCREEN_DETAIL_FAIL';
export const POST_SCREEN_SUCCESS = 'POST_SCREEN_SUCCESS';
export const POST_SCREEN_FAIL = 'POST_SCREEN_FAIL';
export const PUT_SCREEN_SUCCESS = 'PUT_SCREEN_SUCCESS';
export const PUT_SCREEN_FAIL = 'PUT_SCREEN_FAIL';
export const DELETE_SCREEN_SUCCESS = 'DELETE_SCREEN_SUCCESS';
export const DELETE_SCREEN_FAIL = 'DELETE_SCREEN_FAIL';
export const START_QUERY = 'START_QUERY';
