// lấy toàn bộ danh sách người dùng

export const GET_ALL_SEASON_SUCCESS = 'GET_ALL_SEASON_SUCCESS';
export const GET_ALL_SEASON_FAIL = 'GET_ALL_SEASON_FAIL';
export const GET_SEASON_DETAIL_SUCCESS = 'GET_SEASON_DETAIL_SUCCESS';
export const GET_SEASON_DETAIL_FAIL = 'GET_SEASON_DETAIL_FAIL';
export const POST_SEASON_SUCCESS = 'POST_SEASON_SUCCESS';
export const POST_SEASON_FAIL = 'POST_SEASON_FAIL';
export const PUT_SEASON_SUCCESS = 'PUT_SEASON_SUCCESS';
export const PUT_SEASON_FAIL = 'PUT_SEASON_FAIL';
export const DELETE_SEASON_SUCCESS = 'DELETE_SEASON_SUCCESS';
export const DELETE_SEASON_FAIL = 'DELETE_SEASON_FAIL';
export const START_QUERY = 'START_QUERY';
