// lấy toàn bộ danh sách người dùng

export const GET_ALL_SKINTYPE_SUCCESS = 'GET_ALL_SKINTYPE_SUCCESS';
export const GET_ALL_SKINTYPE_FAIL = 'GET_ALL_SKINTYPE_FAIL';
export const GET_SKINTYPE_DETAIL_SUCCESS = 'GET_SKINTYPE_DETAIL_SUCCESS';
export const GET_SKINTYPE_DETAIL_FAIL = 'GET_SKINTYPE_DETAIL_FAIL';
export const POST_SKINTYPE_SUCCESS = 'POST_SKINTYPE_SUCCESS';
export const POST_SKINTYPE_FAIL = 'POST_SKINTYPE_FAIL';
export const PUT_SKINTYPE_SUCCESS = 'PUT_SKINTYPE_SUCCESS';
export const PUT_SKINTYPE_FAIL = 'PUT_SKINTYPE_FAIL';
export const DELETE_SKINTYPE_SUCCESS = 'DELETE_SKINTYPE_SUCCESS';
export const DELETE_SKINTYPE_FAIL = 'DELETE_SKINTYPE_FAIL';
export const START_QUERY = 'START_QUERY';
