// lấy toàn bộ danh sách người dùng

export const GET_ALL_STICKERSTYLE_SUCCESS = 'GET_ALL_STICKERSTYLE_SUCCESS';
export const GET_ALL_STICKERSTYLE_FAIL = 'GET_ALL_STICKERSTYLE_FAIL';
export const GET_STICKERSTYLE_DETAIL_SUCCESS = 'GET_STICKERSTYLE_DETAIL_SUCCESS';
export const GET_STICKERSTYLE_DETAIL_FAIL = 'GET_STICKERSTYLE_DETAIL_FAIL';
export const POST_STICKERSTYLE_SUCCESS = 'POST_STICKERSTYLE_SUCCESS';
export const POST_STICKERSTYLE_FAIL = 'POST_STICKERSTYLE_FAIL';
export const PUT_STICKERSTYLE_SUCCESS = 'PUT_STICKERSTYLE_SUCCESS';
export const PUT_STICKERSTYLE_FAIL = 'PUT_STICKERSTYLE_FAIL';
export const DELETE_STICKERSTYLE_SUCCESS = 'DELETE_STICKERSTYLE_SUCCESS';
export const DELETE_STICKERSTYLE_FAIL = 'DELETE_STICKERSTYLE_FAIL';
export const START_QUERY = 'START_QUERY';
