// lấy toàn bộ danh sách người dùng

export const GET_ALL_STORAGECAPACITY_SUCCESS = 'GET_ALL_STORAGECAPACITY_SUCCESS';
export const GET_ALL_STORAGECAPACITY_FAIL = 'GET_ALL_STORAGECAPACITY_FAIL';
export const GET_STORAGECAPACITY_DETAIL_SUCCESS = 'GET_STORAGECAPACITY_DETAIL_SUCCESS';
export const GET_STORAGECAPACITY_DETAIL_FAIL = 'GET_STORAGECAPACITY_DETAIL_FAIL';
export const POST_STORAGECAPACITY_SUCCESS = 'POST_STORAGECAPACITY_SUCCESS';
export const POST_STORAGECAPACITY_FAIL = 'POST_STORAGECAPACITY_FAIL';
export const PUT_STORAGECAPACITY_SUCCESS = 'PUT_STORAGECAPACITY_SUCCESS';
export const PUT_STORAGECAPACITY_FAIL = 'PUT_STORAGECAPACITY_FAIL';
export const DELETE_STORAGECAPACITY_SUCCESS = 'DELETE_STORAGECAPACITY_SUCCESS';
export const DELETE_STORAGECAPACITY_FAIL = 'DELETE_STORAGECAPACITY_FAIL';
export const START_QUERY = 'START_QUERY';
