// lấy toàn bộ danh sách người dùng

export const GET_ALL_STYLE_SUCCESS = 'GET_ALL_STYLE_SUCCESS';
export const GET_ALL_STYLE_FAIL = 'GET_ALL_STYLE_FAIL';
export const GET_STYLE_DETAIL_SUCCESS = 'GET_STYLE_DETAIL_SUCCESS';
export const GET_STYLE_DETAIL_FAIL = 'GET_STYLE_DETAIL_FAIL';
export const POST_STYLE_SUCCESS = 'POST_STYLE_SUCCESS';
export const POST_STYLE_FAIL = 'POST_STYLE_FAIL';
export const PUT_STYLE_SUCCESS = 'PUT_STYLE_SUCCESS';
export const PUT_STYLE_FAIL = 'PUT_STYLE_FAIL';
export const DELETE_STYLE_SUCCESS = 'DELETE_STYLE_SUCCESS';
export const DELETE_STYLE_FAIL = 'DELETE_STYLE_FAIL';
export const START_QUERY = 'START_QUERY';
