// lấy toàn bộ danh sách người dùng

export const GET_ALL_TYPELOCK_SUCCESS = 'GET_ALL_TYPELOCK_SUCCESS';
export const GET_ALL_TYPELOCK_FAIL = 'GET_ALL_TYPELOCK_FAIL';
export const GET_TYPELOCK_DETAIL_SUCCESS = 'GET_TYPELOCK_DETAIL_SUCCESS';
export const GET_TYPELOCK_DETAIL_FAIL = 'GET_TYPELOCK_DETAIL_FAIL';
export const POST_TYPELOCK_SUCCESS = 'POST_TYPELOCK_SUCCESS';
export const POST_TYPELOCK_FAIL = 'POST_TYPELOCK_FAIL';
export const PUT_TYPELOCK_SUCCESS = 'PUT_TYPELOCK_SUCCESS';
export const PUT_TYPELOCK_FAIL = 'PUT_TYPELOCK_FAIL';
export const DELETE_TYPELOCK_SUCCESS = 'DELETE_TYPELOCK_SUCCESS';
export const DELETE_TYPELOCK_FAIL = 'DELETE_TYPELOCK_FAIL';
export const START_QUERY = 'START_QUERY';
