// lấy toàn bộ danh sách người dùng

export const GET_ALL_TYPEWARRANTY_SUCCESS = 'GET_ALL_TYPEWARRANTY_SUCCESS';
export const GET_ALL_TYPEWARRANTY_FAIL = 'GET_ALL_TYPEWARRANTY_FAIL';
export const GET_TYPEWARRANTY_DETAIL_SUCCESS = 'GET_TYPEWARRANTY_DETAIL_SUCCESS';
export const GET_TYPEWARRANTY_DETAIL_FAIL = 'GET_TYPEWARRANTY_DETAIL_FAIL';
export const POST_TYPEWARRANTY_SUCCESS = 'POST_TYPEWARRANTY_SUCCESS';
export const POST_TYPEWARRANTY_FAIL = 'POST_TYPEWARRANTY_FAIL';
export const PUT_TYPEWARRANTY_SUCCESS = 'PUT_TYPEWARRANTY_SUCCESS';
export const PUT_TYPEWARRANTY_FAIL = 'PUT_TYPEWARRANTY_FAIL';
export const DELETE_TYPEWARRANTY_SUCCESS = 'DELETE_TYPEWARRANTY_SUCCESS';
export const DELETE_TYPEWARRANTY_FAIL = 'DELETE_TYPEWARRANTY_FAIL';
export const START_QUERY = 'START_QUERY';
