// lấy toàn bộ danh sách người dùng

export const GET_ALL_TYPEDEVICE_SUCCESS = 'GET_ALL_TYPEDEVICE_SUCCESS';
export const GET_ALL_TYPEDEVICE_FAIL = 'GET_ALL_TYPEDEVICE_FAIL';
export const GET_TYPEDEVICE_DETAIL_SUCCESS = 'GET_TYPEDEVICE_DETAIL_SUCCESS';
export const GET_TYPEDEVICE_DETAIL_FAIL = 'GET_TYPEDEVICE_DETAIL_FAIL';
export const POST_TYPEDEVICE_SUCCESS = 'POST_TYPEDEVICE_SUCCESS';
export const POST_TYPEDEVICE_FAIL = 'POST_TYPEDEVICE_FAIL';
export const PUT_TYPEDEVICE_SUCCESS = 'PUT_TYPEDEVICE_SUCCESS';
export const PUT_TYPEDEVICE_FAIL = 'PUT_TYPEDEVICE_FAIL';
export const DELETE_TYPEDEVICE_SUCCESS = 'DELETE_TYPEDEVICE_SUCCESS';
export const DELETE_TYPEDEVICE_FAIL = 'DELETE_TYPEDEVICE_FAIL';
export const START_QUERY = 'START_QUERY';
