// lấy toàn bộ danh sách người dùng

export const GET_ALL_TYPESHELL_SUCCESS = 'GET_ALL_TYPESHELL_SUCCESS';
export const GET_ALL_TYPESHELL_FAIL = 'GET_ALL_TYPESHELL_FAIL';
export const GET_TYPESHELL_DETAIL_SUCCESS = 'GET_TYPESHELL_DETAIL_SUCCESS';
export const GET_TYPESHELL_DETAIL_FAIL = 'GET_TYPESHELL_DETAIL_FAIL';
export const POST_TYPESHELL_SUCCESS = 'POST_TYPESHELL_SUCCESS';
export const POST_TYPESHELL_FAIL = 'POST_TYPESHELL_FAIL';
export const PUT_TYPESHELL_SUCCESS = 'PUT_TYPESHELL_SUCCESS';
export const PUT_TYPESHELL_FAIL = 'PUT_TYPESHELL_FAIL';
export const DELETE_TYPESHELL_SUCCESS = 'DELETE_TYPESHELL_SUCCESS';
export const DELETE_TYPESHELL_FAIL = 'DELETE_TYPESHELL_FAIL';
export const START_QUERY = 'START_QUERY';
