// lấy toàn bộ danh sách người dùng

export const GET_ALL_WARRANTYPERIOD_SUCCESS = 'GET_ALL_WARRANTYPERIOD_SUCCESS';
export const GET_ALL_WARRANTYPERIOD_FAIL = 'GET_ALL_WARRANTYPERIOD_FAIL';
export const GET_WARRANTYPERIOD_DETAIL_SUCCESS = 'GET_WARRANTYPERIOD_DETAIL_SUCCESS';
export const GET_WARRANTYPERIOD_DETAIL_FAIL = 'GET_WARRANTYPERIOD_DETAIL_FAIL';
export const POST_WARRANTYPERIOD_SUCCESS = 'POST_WARRANTYPERIOD_SUCCESS';
export const POST_WARRANTYPERIOD_FAIL = 'POST_WARRANTYPERIOD_FAIL';
export const PUT_WARRANTYPERIOD_SUCCESS = 'PUT_WARRANTYPERIOD_SUCCESS';
export const PUT_WARRANTYPERIOD_FAIL = 'PUT_WARRANTYPERIOD_FAIL';
export const DELETE_WARRANTYPERIOD_SUCCESS = 'DELETE_WARRANTYPERIOD_SUCCESS';
export const DELETE_WARRANTYPERIOD_FAIL = 'DELETE_WARRANTYPERIOD_FAIL';
export const START_QUERY = 'START_QUERY';
