// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';

export const GET_ALL_COLORADMIN_SUCCESS = "GET_ALL_COLORADMIN_SUCCESS";
export const GET_ALL_COLORADMIN_FAIL = "GET_ALL_COLORADMIN_FAIL";
export const GET_ALL_COLORADMIN_ADMIN_SUCCESS = "GET_ALL_COLORADMIN_ADMIN_SUCCESS";
export const GET_ALL_COLORADMIN_ADMIN_FAIL = "GET_ALL_COLORADMIN_ADMIN_FAIL";
export const GET_ALL_COLORADMIN_ADMIN_ACCOUNT_SUCCESS = "GET_ALL_COLORADMIN_ADMIN_ACCOUNT_SUCCESS";
export const GET_ALL_COLORADMIN_ADMIN_ACCOUNT_FAIL = "GET_ALL_COLORADMIN_ADMIN_ACCOUNT_FAIL";
export const GET_COLORADMIN_PAGE_SUCCESS = "GET_COLORADMIN_PAGE_SUCCESS";
export const GET_COLORADMIN_PAGE_FAIL = "GET_COLORADMIN_PAGE_FAIL";
export const GET_COLORADMIN_DETAIL_SUCCESS = "GET_COLORADMIN_DETAIL_SUCCESS";
export const GET_COLORADMIN_DETAIL_FAIL = "GET_COLORADMIN_DETAIL_FAIL";
export const SEARCH_COLORADMIN_SUCCESS = "SEARCH_COLORADMIN_SUCCESS";
export const SEARCH_COLORADMIN_FAIL = "SEARCH_COLORADMIN_FAIL";
export const POST_COLORADMIN_SUCCESS = "POST_COLORADMIN_SUCCESS";
export const POST_COLORADMIN_FAIL = "POST_COLORADMIN_FAIL";
export const PUT_COLORADMIN_SUCCESS = "PUT_COLORADMIN_SUCCESS";
export const PUT_COLORADMIN_FAIL = "PUT_COLORADMIN_FAIL";
export const DELETE_COLORADMIN_SUCCESS = "DELETE_COLORADMIN_SUCCESS";
export const DELETE_COLORADMIN_FAIL = "DELETE_COLORADMIN_FAIL";
export const CLOSE_COLORADMIN = "CLOSE_COLORADMIN";
