// lấy toàn bộ danh sách người dùng


export const GET_ALL_CONVERSATION_SUCCESS = "GET_ALL_CONVERSATION_SUCCESS";
export const GET_ALL_CONVERSATION_FAIL = "GET_ALL_CONVERSATION_FAIL";
export const GET_ALL_CONVERSATION_ADMIN_SUCCESS = "GET_ALL_CONVERSATION_ADMIN_SUCCESS";
export const GET_ALL_CONVERSATION_ADMIN_FAIL = "GET_ALL_CONVERSATION_ADMIN_FAIL";
export const GET_ALL_CONVERSATION_ADMIN_ACCOUNT_SUCCESS = "GET_ALL_CONVERSATION_ADMIN_ACCOUNT_SUCCESS";
export const GET_ALL_CONVERSATION_ADMIN_ACCOUNT_FAIL = "GET_ALL_CONVERSATION_ADMIN_ACCOUNT_FAIL";
export const GET_CONVERSATION_PAGE_SUCCESS = "GET_CONVERSATION_PAGE_SUCCESS";
export const GET_CONVERSATION_PAGE_FAIL = "GET_CONVERSATION_PAGE_FAIL";
export const GET_CONVERSATION_DETAIL_SUCCESS = "GET_CONVERSATION_DETAIL_SUCCESS";
export const GET_CONVERSATION_DETAIL_FAIL = "GET_CONVERSATION_DETAIL_FAIL";
export const SEARCH_CONVERSATION_SUCCESS = "SEARCH_CONVERSATION_SUCCESS";
export const SEARCH_CONVERSATION_FAIL = "SEARCH_CONVERSATION_FAIL";
export const POST_CONVERSATION_SUCCESS = "POST_CONVERSATION_SUCCESS";
export const POST_CONVERSATION_FAIL = "POST_CONVERSATION_FAIL";
export const PUT_CONVERSATION_SUCCESS = "PUT_CONVERSATION_SUCCESS";
export const PUT_CONVERSATION_FAIL = "PUT_CONVERSATION_FAIL";
export const DELETE_CONVERSATION_SUCCESS = "DELETE_CONVERSATION_SUCCESS";
export const DELETE_CONVERSATION_FAIL = "DELETE_CONVERSATION_FAIL";
export const CLOSE_CONVERSATION = "CLOSE_CONVERSATION";
