// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';

export const GET_ALL_DELIVERYMETHOD_SUCCESS = "GET_ALL_DELIVERYMETHOD_SUCCESS";
export const GET_ALL_DELIVERYMETHOD_FAIL = "GET_ALL_DELIVERYMETHOD_FAIL";
export const GET_ALL_DELIVERYMETHOD_ADMIN_SUCCESS = "GET_ALL_DELIVERYMETHOD_ADMIN_SUCCESS";
export const GET_ALL_DELIVERYMETHOD_ADMIN_FAIL = "GET_ALL_DELIVERYMETHOD_ADMIN_FAIL";
export const GET_ALL_DELIVERYMETHOD_ADMIN_ACCOUNT_SUCCESS = "GET_ALL_DELIVERYMETHOD_ADMIN_ACCOUNT_SUCCESS";
export const GET_ALL_DELIVERYMETHOD_ADMIN_ACCOUNT_FAIL = "GET_ALL_DELIVERYMETHOD_ADMIN_ACCOUNT_FAIL";
export const GET_DELIVERYMETHOD_PAGE_SUCCESS = "GET_DELIVERYMETHOD_PAGE_SUCCESS";
export const GET_DELIVERYMETHOD_PAGE_FAIL = "GET_DELIVERYMETHOD_PAGE_FAIL";
export const GET_DELIVERYMETHOD_DETAIL_SUCCESS = "GET_DELIVERYMETHOD_DETAIL_SUCCESS";
export const GET_DELIVERYMETHOD_DETAIL_FAIL = "GET_DELIVERYMETHOD_DETAIL_FAIL";
export const SEARCH_DELIVERYMETHOD_SUCCESS = "SEARCH_DELIVERYMETHOD_SUCCESS";
export const SEARCH_DELIVERYMETHOD_FAIL = "SEARCH_DELIVERYMETHOD_FAIL";
export const POST_DELIVERYMETHOD_SUCCESS = "POST_DELIVERYMETHOD_SUCCESS";
export const POST_DELIVERYMETHOD_FAIL = "POST_DELIVERYMETHOD_FAIL";
export const PUT_DELIVERYMETHOD_SUCCESS = "PUT_DELIVERYMETHOD_SUCCESS";
export const PUT_DELIVERYMETHOD_FAIL = "PUT_DELIVERYMETHOD_FAIL";
export const DELETE_DELIVERYMETHOD_SUCCESS = "DELETE_DELIVERYMETHOD_SUCCESS";
export const DELETE_DELIVERYMETHOD_FAIL = "DELETE_DELIVERYMETHOD_FAIL";
export const CLOSE_DELIVERYMETHOD = "CLOSE_DELIVERYMETHOD";
