// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';

export const GET_ALL_SIZEADMIN_SUCCESS = "GET_ALL_SIZEADMIN_SUCCESS";
export const GET_ALL_SIZEADMIN_FAIL = "GET_ALL_SIZEADMIN_FAIL";
export const GET_ALL_SIZEADMIN_ADMIN_SUCCESS = "GET_ALL_SIZEADMIN_ADMIN_SUCCESS";
export const GET_ALL_SIZEADMIN_ADMIN_FAIL = "GET_ALL_SIZEADMIN_ADMIN_FAIL";
export const GET_ALL_SIZEADMIN_ADMIN_ACCOUNT_SUCCESS = "GET_ALL_SIZEADMIN_ADMIN_ACCOUNT_SUCCESS";
export const GET_ALL_SIZEADMIN_ADMIN_ACCOUNT_FAIL = "GET_ALL_SIZEADMIN_ADMIN_ACCOUNT_FAIL";
export const GET_SIZEADMIN_PAGE_SUCCESS = "GET_SIZEADMIN_PAGE_SUCCESS";
export const GET_SIZEADMIN_PAGE_FAIL = "GET_SIZEADMIN_PAGE_FAIL";
export const GET_SIZEADMIN_DETAIL_SUCCESS = "GET_SIZEADMIN_DETAIL_SUCCESS";
export const GET_SIZEADMIN_DETAIL_FAIL = "GET_SIZEADMIN_DETAIL_FAIL";
export const SEARCH_SIZEADMIN_SUCCESS = "SEARCH_SIZEADMIN_SUCCESS";
export const SEARCH_SIZEADMIN_FAIL = "SEARCH_SIZEADMIN_FAIL";
export const POST_SIZEADMIN_SUCCESS = "POST_SIZEADMIN_SUCCESS";
export const POST_SIZEADMIN_FAIL = "POST_SIZEADMIN_FAIL";
export const PUT_SIZEADMIN_SUCCESS = "PUT_SIZEADMIN_SUCCESS";
export const PUT_SIZEADMIN_FAIL = "PUT_SIZEADMIN_FAIL";
export const DELETE_SIZEADMIN_SUCCESS = "DELETE_SIZEADMIN_SUCCESS";
export const DELETE_SIZEADMIN_FAIL = "DELETE_SIZEADMIN_FAIL";
export const CLOSE_SIZEADMIN = "CLOSE_SIZEADMIN";
