// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';

export const GET_ALL_USAGESTATUS_SUCCESS = "GET_ALL_USAGESTATUS_SUCCESS";
export const GET_ALL_USAGESTATUS_FAIL = "GET_ALL_USAGESTATUS_FAIL";
export const GET_ALL_USAGESTATUS_ADMIN_SUCCESS = "GET_ALL_USAGESTATUS_ADMIN_SUCCESS";
export const GET_ALL_USAGESTATUS_ADMIN_FAIL = "GET_ALL_USAGESTATUS_ADMIN_FAIL";
export const GET_ALL_USAGESTATUS_ADMIN_ACCOUNT_SUCCESS = "GET_ALL_USAGESTATUS_ADMIN_ACCOUNT_SUCCESS";
export const GET_ALL_USAGESTATUS_ADMIN_ACCOUNT_FAIL = "GET_ALL_USAGESTATUS_ADMIN_ACCOUNT_FAIL";
export const GET_USAGESTATUS_PAGE_SUCCESS = "GET_USAGESTATUS_PAGE_SUCCESS";
export const GET_USAGESTATUS_PAGE_FAIL = "GET_USAGESTATUS_PAGE_FAIL";
export const GET_USAGESTATUS_DETAIL_SUCCESS = "GET_USAGESTATUS_DETAIL_SUCCESS";
export const GET_USAGESTATUS_DETAIL_FAIL = "GET_USAGESTATUS_DETAIL_FAIL";
export const SEARCH_USAGESTATUS_SUCCESS = "SEARCH_USAGESTATUS_SUCCESS";
export const SEARCH_USAGESTATUS_FAIL = "SEARCH_USAGESTATUS_FAIL";
export const POST_USAGESTATUS_SUCCESS = "POST_USAGESTATUS_SUCCESS";
export const POST_USAGESTATUS_FAIL = "POST_USAGESTATUS_FAIL";
export const PUT_USAGESTATUS_SUCCESS = "PUT_USAGESTATUS_SUCCESS";
export const PUT_USAGESTATUS_FAIL = "PUT_USAGESTATUS_FAIL";
export const DELETE_USAGESTATUS_SUCCESS = "DELETE_USAGESTATUS_SUCCESS";
export const DELETE_USAGESTATUS_FAIL = "DELETE_USAGESTATUS_FAIL";
export const CLOSE_USAGESTATUS = "CLOSE_USAGESTATUS";
